version: "3.8"
services:
  react:
    build: ./front
    environment:
      CHOKIDAR_USEPOLLING: "true" 
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    stdin_open: true
    tty: true  
    depends_on: 
      - express

  express:
   build: ./backend
   ports:
     - "8080:8080"
   volumes:
     - ./backend:/app