apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVerison: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
    labels:
      app: front
    spec:
      containers: 
        - name: front
          image: 
          env:
            - name: AUTH_API_ADDRESSS
              value: 'auth-service.default:3000'